"""empty message

Revision ID: 154990c80155
Revises: 530f85cbaa28
Create Date: 2026-05-22 09:55:51.369089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '154990c80155'
down_revision = '530f85cbaa28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classifier_indicator', schema=None) as batch_op:
        batch_op.drop_column('job_server')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classifier_indicator', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_server', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
