"""empty message

Revision ID: 182bc2a22c67
Revises: 154990c80155
Create Date: 2026-05-22 09:56:57.820174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '182bc2a22c67'
down_revision = '154990c80155'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classifier_indicator', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_server', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classifier_indicator', schema=None) as batch_op:
        batch_op.drop_column('job_server')

    # ### end Alembic commands ###
