"""empty message

Revision ID: 3619da8c4768
Revises: 182bc2a22c67
Create Date: 2026-05-22 10:21:02.753705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3619da8c4768'
down_revision = '182bc2a22c67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result_source', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('error_code', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('job_server', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result_source', schema=None) as batch_op:
        batch_op.drop_column('job_server')
        batch_op.drop_column('error_code')
        batch_op.drop_column('created_at')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
