"""empty message

Revision ID: 4ea26b2ce68d
Revises: ed522922a5ea
Create Date: 2026-05-22 11:23:07.031313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ea26b2ce68d'
down_revision = 'ed522922a5ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source', schema=None) as batch_op:
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.drop_column('country')

    # ### end Alembic commands ###
