"""empty message

Revision ID: 530f85cbaa28
Revises: 
Create Date: 2026-05-21 16:59:56.585900

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '530f85cbaa28'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('study_task')
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_answer__participant'))
        batch_op.drop_index(batch_op.f('idx_answer__question'))
        batch_op.drop_index(batch_op.f('idx_answer__result'))
        batch_op.drop_index(batch_op.f('idx_answer__study'))
        batch_op.drop_constraint(batch_op.f('fk_answer__participant'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_answer__study'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_answer__result'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_answer__question'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_answer_result_serp_serp'), 'serp', ['result_serp'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_answer_participant_participant'), 'participant', ['participant'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_answer_result_chatbot_result_chatbot'), 'result_chatbot', ['result_chatbot'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_answer_question_question'), 'question', ['question'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_answer_result_ai_result_ai'), 'result_ai', ['result_ai'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_answer_result_result'), 'result', ['result'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_answer_study_study'), 'study', ['study'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('classifier', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
        batch_op.alter_column('display',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))

    with op.batch_alter_table('classifier_indicator', schema=None) as batch_op:
        batch_op.alter_column('indicator',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('value',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('result',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('classifier',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_classifier_indicator_result'), ['result'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_indicator__result'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_classifier_indicator_result_result'), 'result', ['result'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('job_server')

    with op.batch_alter_table('classifier_result', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_constraint(batch_op.f('unique_classifier_result'), type_='unique')
        batch_op.drop_column('job_server')
        batch_op.drop_column('study')

    with op.batch_alter_table('classifier_study', schema=None) as batch_op:
        batch_op.drop_column('id')

    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('code',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('option', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('label',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_option__question'))
        batch_op.drop_constraint(batch_op.f('fk_option__question'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_option_question_question'), 'question', ['question'], ['id'])

    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('participant_study', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_participant_study'))

    with op.batch_alter_table('qs_geotarget', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
        batch_op.alter_column('canonical_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
        batch_op.alter_column('country_code',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
        batch_op.alter_column('target_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
        batch_op.alter_column('criterion_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('qs_keyword', schema=None) as batch_op:
        batch_op.alter_column('qs_study_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('qs_geotarget_criterion_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('qs_language_code_criterion_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('keyword',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)

    with op.batch_alter_table('qs_keyword_idea', schema=None) as batch_op:
        batch_op.alter_column('qs_study_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('qs_keyword_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('keyword_idea',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
        batch_op.alter_column('avg_monthly_searches',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('competition',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)

    with op.batch_alter_table('qs_language_code', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
        batch_op.alter_column('criterion_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('code')

    with op.batch_alter_table('qs_study', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('qs_study_user', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_qs_study_user_qs_study_qs_study'), 'qs_study', ['qs_study'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_qs_study_user_user_user'), 'user', ['user'], ['id'])
        batch_op.drop_column('id')

    with op.batch_alter_table('query', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assignment_count', sa.Integer(), nullable=True))
        batch_op.alter_column('query',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_query__study'))
        batch_op.drop_constraint(batch_op.f('fk_query__study'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_query_study_study'), 'study', ['study'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('task')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_question__question_template'))
        batch_op.drop_index(batch_op.f('idx_question__question_type'))
        batch_op.drop_index(batch_op.f('idx_question__study'))
        batch_op.drop_constraint(batch_op.f('fk_question__question_type'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_question__study'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_question_question_type_questiontype'), 'questiontype', ['question_type'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_question_study_study'), 'study', ['study'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('question_template')

    with op.batch_alter_table('question_result', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_question_result'))

    with op.batch_alter_table('questiontype', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('display',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('range_study', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_range_study_study_study'), 'study', ['study'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('final_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('main',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('ip',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('origin',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('normalized_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('fki_r'))
        batch_op.drop_index(batch_op.f('idx_result__scraper'))
        batch_op.drop_index(batch_op.f('idx_result__study'))
        batch_op.create_index(batch_op.f('ix_result_normalized_url'), ['normalized_url'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_result__study'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_result__query'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_result_scraper'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_result_resulttype'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_result_scraper_scraper'), 'scraper', ['scraper'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_result_country_country'), 'country', ['country'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_result_study_study'), 'study', ['study'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_result_query_query'), 'query', ['query'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_result_serp_serp'), 'serp', ['serp'], ['id'])
        batch_op.drop_column('resulttype')

    with op.batch_alter_table('result_ai', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('study',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('query',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(batch_op.f('fk_result_ai_scraper_scraper'), 'scraper', ['scraper'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_result_ai_query_query'), 'query', ['query'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_result_ai_study_study'), 'study', ['study'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('result_ai_source', schema=None) as batch_op:
        batch_op.alter_column('url',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('error_code',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('job_server',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('ip',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('result_ai',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(batch_op.f('fk_result_ai_source_study_study'), 'study', ['study'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_result_ai_source_scraper_scraper'), 'scraper', ['scraper'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_result_ai_source_source_source'), 'source', ['source'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_result_ai_source_country_country'), 'country', ['country'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_result_ai_source_query_query'), 'query', ['query'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_result_ai_source_result_ai_result_ai'), 'result_ai', ['result_ai'], ['id'])

    with op.batch_alter_table('result_chatbot', schema=None) as batch_op:
        batch_op.alter_column('answer_html',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('study',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('query',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(batch_op.f('fk_result_chatbot_query_query'), 'query', ['query'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_result_chatbot_scraper_scraper'), 'scraper', ['scraper'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_result_chatbot_study_study'), 'study', ['study'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('result_source', schema=None) as batch_op:
        batch_op.alter_column('result',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('progress',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('uq_result'), type_='unique')
        batch_op.drop_column('error_code')
        batch_op.drop_column('created_at')
        batch_op.drop_column('id')
        batch_op.drop_column('job_server')

    with op.batch_alter_table('resulttype', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('display',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('filter',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('selection',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('permissions',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('scraper', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_scraper__query'))
        batch_op.drop_index(batch_op.f('idx_scraper__search_engine'))
        batch_op.drop_index(batch_op.f('idx_scraper__study'))
        batch_op.drop_constraint(batch_op.f('fk_scraper__study'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_scraper__search_engine'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_scraper__query'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_scraper_study_study'), 'study', ['study'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_scraper_query_query'), 'query', ['query'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_scraper_searchengine_searchengine'), 'searchengine', ['searchengine'], ['id'])

    with op.batch_alter_table('searchengine', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('searchengine_study', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_searchengine_study'))

    with op.batch_alter_table('serp', schema=None) as batch_op:
        batch_op.alter_column('file_path',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_serp__scraper'))
        batch_op.create_index(batch_op.f('ix_serp_query'), ['query'], unique=False)
        batch_op.create_index(batch_op.f('ix_serp_study'), ['study'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_serp_study_study'), 'study', ['study'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_serp_scraper_scraper'), 'scraper', ['scraper'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_serp_query_query'), 'query', ['query'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.alter_column('url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('file_path',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('content_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('error_code',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.drop_column('job_server')
        batch_op.drop_column('content_dict')
        batch_op.drop_column('country')
        batch_op.drop_column('bin')
        batch_op.drop_column('code')

    with op.batch_alter_table('study', schema=None) as batch_op:
        batch_op.add_column(sa.Column('limit_by_query', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('max_queries_per_participant', sa.Integer(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('task',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('skippable',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('group_by_query',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('max_assignments_per_task',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('3'))

    with op.batch_alter_table('study_resulttype', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_study_resulttype_resulttype_resulttype'), 'resulttype', ['resulttype'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_study_resulttype_study_study'), 'study', ['study'], ['id'])

    with op.batch_alter_table('study_url_filter', schema=None) as batch_op:
        batch_op.alter_column('study',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
        batch_op.alter_column('include',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('exclude',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.create_foreign_key(batch_op.f('fk_study_url_filter_study_study'), 'study', ['study'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('study_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_study_user'))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('fs_uniquifier',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('last_login_ip',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('current_login_ip',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('tf_totp_secret',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('tf_primary_method',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('tf_phone_number',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('us_totp_secrets',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('fs_webauthn_user_handle',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('mf_recovery_codes',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('us_phone_number',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.drop_column('affiliation')

    with op.batch_alter_table('user_role', schema=None) as batch_op:
        batch_op.alter_column('user',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('role',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('user_role_relation_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('user_role_relation_1'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_user_role_user_user'), 'user', ['user'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_user_role_role_role'), 'role', ['role'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_role', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_role_role_role'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_user_role_user_user'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('user_role_relation_1'), 'user', ['user'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('user_role_relation_2'), 'role', ['role'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.alter_column('role',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('affiliation', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.alter_column('us_phone_number',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('mf_recovery_codes',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('fs_webauthn_user_handle',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('us_totp_secrets',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('tf_phone_number',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('tf_primary_method',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('tf_totp_secret',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('current_login_ip',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('last_login_ip',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('fs_uniquifier',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('study_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_study_user'), ['user'], unique=False)

    with op.batch_alter_table('study_url_filter', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_study_url_filter_study_study'), type_='foreignkey')
        batch_op.alter_column('exclude',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('include',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('study',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('study_resulttype', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_study_resulttype_study_study'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_study_resulttype_resulttype_resulttype'), type_='foreignkey')

    with op.batch_alter_table('study', schema=None) as batch_op:
        batch_op.alter_column('max_assignments_per_task',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('3'))
        batch_op.alter_column('group_by_query',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('skippable',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('task',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('max_queries_per_participant')
        batch_op.drop_column('limit_by_query')

    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', postgresql.BYTEA(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('bin', postgresql.BYTEA(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('country', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('content_dict', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('job_server', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.alter_column('error_code',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('content_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('file_path',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('serp', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_serp_query_query'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_serp_scraper_scraper'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_serp_study_study'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_serp_study'))
        batch_op.drop_index(batch_op.f('ix_serp_query'))
        batch_op.create_index(batch_op.f('idx_serp__scraper'), ['scraper'], unique=False)
        batch_op.alter_column('file_path',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('searchengine_study', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_searchengine_study'), ['study'], unique=False)

    with op.batch_alter_table('searchengine', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('scraper', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_scraper_searchengine_searchengine'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_scraper_query_query'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_scraper_study_study'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_scraper__query'), 'query', ['query'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_scraper__search_engine'), 'searchengine', ['searchengine'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_scraper__study'), 'study', ['study'], ['id'], ondelete='SET NULL')
        batch_op.create_index(batch_op.f('idx_scraper__study'), ['study'], unique=False)
        batch_op.create_index(batch_op.f('idx_scraper__search_engine'), ['searchengine'], unique=False)
        batch_op.create_index(batch_op.f('idx_scraper__query'), ['query'], unique=False)

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.alter_column('permissions',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('resulttype', schema=None) as batch_op:
        batch_op.alter_column('selection',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('filter',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('display',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('result_source', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_server', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('error_code', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_result'), ['result'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('progress',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('result',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('result_chatbot', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_result_chatbot_study_study'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_result_chatbot_scraper_scraper'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_result_chatbot_query_query'), type_='foreignkey')
        batch_op.alter_column('query',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('study',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('answer_html',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('result_ai_source', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_result_ai_source_result_ai_result_ai'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_result_ai_source_query_query'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_result_ai_source_country_country'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_result_ai_source_source_source'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_result_ai_source_scraper_scraper'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_result_ai_source_study_study'), type_='foreignkey')
        batch_op.alter_column('result_ai',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('ip',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('job_server',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('error_code',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('url',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('result_ai', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_result_ai_study_study'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_result_ai_query_query'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_result_ai_scraper_scraper'), type_='foreignkey')
        batch_op.alter_column('query',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('study',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resulttype', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_result_serp_serp'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_result_query_query'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_result_study_study'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_result_country_country'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_result_scraper_scraper'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_result_resulttype'), 'resulttype', ['resulttype'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_result_scraper'), 'scraper', ['scraper'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_result__query'), 'query', ['query'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_result__study'), 'study', ['study'], ['id'], ondelete='SET NULL')
        batch_op.drop_index(batch_op.f('ix_result_normalized_url'))
        batch_op.create_index(batch_op.f('idx_result__study'), ['study'], unique=False)
        batch_op.create_index(batch_op.f('idx_result__scraper'), ['scraper'], unique=False)
        batch_op.create_index(batch_op.f('fki_r'), ['serp'], unique=False)
        batch_op.alter_column('normalized_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('origin',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('ip',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('main',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('final_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('range_study', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_range_study_study_study'), type_='foreignkey')

    with op.batch_alter_table('questiontype', schema=None) as batch_op:
        batch_op.alter_column('display',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('question_result', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_question_result'), ['result'], unique=False)

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_template', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_question_study_study'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_question_question_type_questiontype'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_question__study'), 'study', ['study'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_question__question_type'), 'questiontype', ['question_type'], ['id'], ondelete='SET NULL')
        batch_op.create_index(batch_op.f('idx_question__study'), ['study'], unique=False)
        batch_op.create_index(batch_op.f('idx_question__question_type'), ['question_type'], unique=False)
        batch_op.create_index(batch_op.f('idx_question__question_template'), ['question_template'], unique=False)
        batch_op.alter_column('description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('query', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_query_study_study'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_query__study'), 'study', ['study'], ['id'], ondelete='SET NULL')
        batch_op.create_index(batch_op.f('idx_query__study'), ['study'], unique=False)
        batch_op.alter_column('description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('query',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('assignment_count')

    with op.batch_alter_table('qs_study_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_qs_study_user_user_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_qs_study_user_qs_study_qs_study'), type_='foreignkey')

    with op.batch_alter_table('qs_study', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('qs_language_code', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.alter_column('criterion_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('qs_keyword_idea', schema=None) as batch_op:
        batch_op.alter_column('competition',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('avg_monthly_searches',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('keyword_idea',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('qs_keyword_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('qs_study_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('qs_keyword', schema=None) as batch_op:
        batch_op.alter_column('keyword',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('qs_language_code_criterion_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('qs_geotarget_criterion_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('qs_study_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('qs_geotarget', schema=None) as batch_op:
        batch_op.alter_column('criterion_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('target_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('country_code',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('canonical_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('participant_study', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_participant_study'), ['study'], unique=False)

    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('option', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_option_question_question'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_option__question'), 'question', ['question'], ['id'], ondelete='SET NULL')
        batch_op.create_index(batch_op.f('idx_option__question'), ['question'], unique=False)
        batch_op.alter_column('label',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('value',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('classifier_study', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('classifier_study_id_seq'::regclass)"), autoincrement=True, nullable=False))

    with op.batch_alter_table('classifier_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('study', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('job_server', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint(batch_op.f('unique_classifier_result'), ['classifier', 'result'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('value',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('classifier_indicator', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_server', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_classifier_indicator_result_result'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_indicator__result'), 'result', ['result'], ['id'])
        batch_op.drop_index(batch_op.f('ix_classifier_indicator_result'))
        batch_op.alter_column('classifier',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('result',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('value',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('indicator',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('classifier', schema=None) as batch_op:
        batch_op.alter_column('display',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_answer_study_study'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_answer_result_result'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_answer_result_ai_result_ai'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_answer_question_question'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_answer_result_chatbot_result_chatbot'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_answer_participant_participant'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_answer_result_serp_serp'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_answer__question'), 'question', ['question'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_answer__result'), 'result', ['result'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_answer__study'), 'study', ['study'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_answer__participant'), 'participant', ['participant'], ['id'], ondelete='SET NULL')
        batch_op.create_index(batch_op.f('idx_answer__study'), ['study'], unique=False)
        batch_op.create_index(batch_op.f('idx_answer__result'), ['result'], unique=False)
        batch_op.create_index(batch_op.f('idx_answer__question'), ['question'], unique=False)
        batch_op.create_index(batch_op.f('idx_answer__participant'), ['participant'], unique=False)
        batch_op.alter_column('value',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    op.create_table('study_task',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('study', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('task', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('study_task_pkey'))
    )
    # ### end Alembic commands ###
