"""empty message

Revision ID: 5f31e2b8630b
Revises: 9e498d071fc9
Create Date: 2026-05-22 11:48:10.809950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f31e2b8630b'
down_revision = '9e498d071fc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study', schema=None) as batch_op:
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_assignments_per_task', sa.INTEGER(), server_default=sa.text('3'), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
