"""empty message

Revision ID: 9e498d071fc9
Revises: 9ad677255539
Create Date: 2026-05-22 11:27:01.357113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e498d071fc9'
down_revision = '9ad677255539'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source', schema=None) as batch_op:
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.drop_column('content_dict')

    # ### end Alembic commands ###
