"""empty message

Revision ID: bf6b865ad252
Revises: 5f31e2b8630b
Create Date: 2026-06-01 10:47:46.544880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf6b865ad252'
down_revision = '5f31e2b8630b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.create_index('idx_answer_lookup', ['participant', 'study', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_answer_study'), ['study'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_answer_result_ai_result_ai'), 'result_ai', ['result_ai'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_answer_result_serp_serp'), 'serp', ['result_serp'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_answer_result_chatbot_result_chatbot'), 'result_chatbot', ['result_chatbot'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_answer_participant_participant'), 'participant', ['participant'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_answer_study_study'), 'study', ['study'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_answer_question_question'), 'question', ['question'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_answer_result_result'), 'result', ['result'], ['id'])

    with op.batch_alter_table('classifier_indicator', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classifier_indicator_result'), ['result'], unique=False)
        batch_op.create_index(batch_op.f('ix_classifier_indicator_study'), ['study'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_classifier_indicator_study_study'), 'study', ['study'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_classifier_indicator_result_result'), 'result', ['result'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_classifier_indicator_classifier_classifier'), 'classifier', ['classifier'], ['id'])

    with op.batch_alter_table('classifier_result', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classifier_result_study'), ['study'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_classifier_result_classifier_classifier'), 'classifier', ['classifier'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_classifier_result_study_study'), 'study', ['study'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_classifier_result_result_result'), 'result', ['result'], ['id'])

    with op.batch_alter_table('classifier_study', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_classifier_study_study_study'), 'study', ['study'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_classifier_study_classifier_classifier'), 'classifier', ['classifier'], ['id'])

    with op.batch_alter_table('option', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_option_question_question'), 'question', ['question'], ['id'])

    with op.batch_alter_table('participant_study', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_participant_study_study_study'), 'study', ['study'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_participant_study_participant_participant'), 'participant', ['participant'], ['id'])

    with op.batch_alter_table('qs_study_user', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_qs_study_user_user_user'), 'user', ['user'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_qs_study_user_qs_study_qs_study'), 'qs_study', ['qs_study'], ['id'])

    with op.batch_alter_table('query', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_query_study'), ['study'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_query_study_study'), 'study', ['study'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_study'), ['study'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_question_question_type_questiontype'), 'questiontype', ['question_type'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_question_study_study'), 'study', ['study'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('question_result', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_question_result_question_question'), 'question', ['question'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_question_result_result_result'), 'result', ['result'], ['id'])

    with op.batch_alter_table('range_study', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_range_study_study'), ['study'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_range_study_study_study'), 'study', ['study'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_result_normalized_url'), ['normalized_url'], unique=False)
        batch_op.create_index(batch_op.f('ix_result_study'), ['study'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_result_query_query'), 'query', ['query'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_result_study_study'), 'study', ['study'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_result_scraper_scraper'), 'scraper', ['scraper'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_result_serp_serp'), 'serp', ['serp'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_result_country_country'), 'country', ['country'], ['id'])

    with op.batch_alter_table('result_ai', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_result_ai_study'), ['study'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_result_ai_query_query'), 'query', ['query'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_result_ai_study_study'), 'study', ['study'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_result_ai_scraper_scraper'), 'scraper', ['scraper'], ['id'])

    with op.batch_alter_table('result_ai_source', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_result_ai_source_study'), ['study'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_result_ai_source_study_study'), 'study', ['study'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_result_ai_source_result_ai_result_ai'), 'result_ai', ['result_ai'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_result_ai_source_scraper_scraper'), 'scraper', ['scraper'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_result_ai_source_query_query'), 'query', ['query'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_result_ai_source_source_source'), 'source', ['source'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_result_ai_source_country_country'), 'country', ['country'], ['id'])

    with op.batch_alter_table('result_chatbot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_result_chatbot_study'), ['study'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_result_chatbot_study_study'), 'study', ['study'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_result_chatbot_scraper_scraper'), 'scraper', ['scraper'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_result_chatbot_query_query'), 'query', ['query'], ['id'])

    with op.batch_alter_table('result_source', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_result_source_result_result'), 'result', ['result'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_result_source_source_source'), 'source', ['source'], ['id'])

    with op.batch_alter_table('scraper', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scraper_study'), ['study'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_scraper_study_study'), 'study', ['study'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_scraper_searchengine_searchengine'), 'searchengine', ['searchengine'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_scraper_query_query'), 'query', ['query'], ['id'])

    with op.batch_alter_table('searchengine_study', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_searchengine_study_study_study'), 'study', ['study'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_searchengine_study_searchengine_searchengine'), 'searchengine', ['searchengine'], ['id'])

    with op.batch_alter_table('serp', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_serp_query'), ['query'], unique=False)
        batch_op.create_index(batch_op.f('ix_serp_study'), ['study'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_serp_query_query'), 'query', ['query'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_serp_study_study'), 'study', ['study'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_serp_scraper_scraper'), 'scraper', ['scraper'], ['id'])

    with op.batch_alter_table('study_resulttype', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_study_resulttype_study_study'), 'study', ['study'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_study_resulttype_resulttype_resulttype'), 'resulttype', ['resulttype'], ['id'])

    with op.batch_alter_table('study_url_filter', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_study_url_filter_study'), ['study'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_study_url_filter_study_study'), 'study', ['study'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('study_user', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_study_user_study_study'), 'study', ['study'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_study_user_user_user'), 'user', ['user'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('force_password_change', sa.Boolean(), nullable=False))

    with op.batch_alter_table('user_role', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_user_role_user_user'), 'user', ['user'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_user_role_role_role'), 'role', ['role'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_role', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_role_role_role'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_user_role_user_user'), type_='foreignkey')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('force_password_change')

    with op.batch_alter_table('study_user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_study_user_user_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_study_user_study_study'), type_='foreignkey')

    with op.batch_alter_table('study_url_filter', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_study_url_filter_study_study'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_study_url_filter_study'))

    with op.batch_alter_table('study_resulttype', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_study_resulttype_resulttype_resulttype'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_study_resulttype_study_study'), type_='foreignkey')

    with op.batch_alter_table('serp', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_serp_scraper_scraper'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_serp_study_study'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_serp_query_query'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_serp_study'))
        batch_op.drop_index(batch_op.f('ix_serp_query'))

    with op.batch_alter_table('searchengine_study', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_searchengine_study_searchengine_searchengine'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_searchengine_study_study_study'), type_='foreignkey')

    with op.batch_alter_table('scraper', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_scraper_query_query'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_scraper_searchengine_searchengine'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_scraper_study_study'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_scraper_study'))

    with op.batch_alter_table('result_source', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_result_source_source_source'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_result_source_result_result'), type_='foreignkey')

    with op.batch_alter_table('result_chatbot', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_result_chatbot_query_query'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_result_chatbot_scraper_scraper'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_result_chatbot_study_study'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_result_chatbot_study'))

    with op.batch_alter_table('result_ai_source', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_result_ai_source_country_country'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_result_ai_source_source_source'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_result_ai_source_query_query'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_result_ai_source_scraper_scraper'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_result_ai_source_result_ai_result_ai'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_result_ai_source_study_study'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_result_ai_source_study'))

    with op.batch_alter_table('result_ai', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_result_ai_scraper_scraper'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_result_ai_study_study'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_result_ai_query_query'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_result_ai_study'))

    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_result_country_country'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_result_serp_serp'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_result_scraper_scraper'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_result_study_study'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_result_query_query'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_result_study'))
        batch_op.drop_index(batch_op.f('ix_result_normalized_url'))

    with op.batch_alter_table('range_study', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_range_study_study_study'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_range_study_study'))

    with op.batch_alter_table('question_result', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_question_result_result_result'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_question_result_question_question'), type_='foreignkey')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_question_study_study'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_question_question_type_questiontype'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_question_study'))

    with op.batch_alter_table('query', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_query_study_study'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_query_study'))

    with op.batch_alter_table('qs_study_user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_qs_study_user_qs_study_qs_study'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_qs_study_user_user_user'), type_='foreignkey')

    with op.batch_alter_table('participant_study', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_participant_study_participant_participant'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_participant_study_study_study'), type_='foreignkey')

    with op.batch_alter_table('option', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_option_question_question'), type_='foreignkey')

    with op.batch_alter_table('classifier_study', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_classifier_study_classifier_classifier'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_classifier_study_study_study'), type_='foreignkey')

    with op.batch_alter_table('classifier_result', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_classifier_result_result_result'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_classifier_result_study_study'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_classifier_result_classifier_classifier'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_classifier_result_study'))

    with op.batch_alter_table('classifier_indicator', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_classifier_indicator_classifier_classifier'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_classifier_indicator_result_result'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_classifier_indicator_study_study'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_classifier_indicator_study'))
        batch_op.drop_index(batch_op.f('ix_classifier_indicator_result'))

    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_answer_result_result'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_answer_question_question'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_answer_study_study'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_answer_participant_participant'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_answer_result_chatbot_result_chatbot'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_answer_result_serp_serp'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_answer_result_ai_result_ai'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_answer_study'))
        batch_op.drop_index('idx_answer_lookup')

    # ### end Alembic commands ###
