"""empty message

Revision ID: ed522922a5ea
Revises: fb32ef7947d9
Create Date: 2026-05-22 11:14:52.950846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed522922a5ea'
down_revision = 'fb32ef7947d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result_source', schema=None) as batch_op:
        batch_op.alter_column('result',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result_source', schema=None) as batch_op:
        batch_op.alter_column('result',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
