"""empty message

Revision ID: fb32ef7947d9
Revises: 3619da8c4768
Create Date: 2026-05-22 10:32:12.298532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb32ef7947d9'
down_revision = '3619da8c4768'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classifier_indicator', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classifier_indicator_study'), ['study'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_classifier_indicator_study_study'), 'study', ['study'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('classifier_result', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classifier_result_study'), ['study'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_classifier_result_study_study'), 'study', ['study'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classifier_result', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_classifier_result_study_study'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_classifier_result_study'))
        batch_op.drop_column('study')
        batch_op.drop_column('job_server')

    with op.batch_alter_table('classifier_indicator', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_classifier_indicator_study_study'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_classifier_indicator_study'))
        batch_op.drop_column('study')

    # ### end Alembic commands ###
